"""Add fuel_prices table for spend conversion

Revision ID: 9f1327182331
Revises: 738a0870ff11
Create Date: 2026-01-14 09:26:06.662306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f1327182331'
down_revision: Union[str, None] = '738a0870ff11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fuel_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_prices_fuel_type'), 'fuel_prices', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_fuel_prices_region'), 'fuel_prices', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_prices_region'), table_name='fuel_prices')
    op.drop_index(op.f('ix_fuel_prices_fuel_type'), table_name='fuel_prices')
    op.drop_table('fuel_prices')
    # ### end Alembic commands ###
