"""Initial schema with resolution_strategy

Revision ID: aa836b07dfe6
Revises: 
Create Date: 2026-01-12 19:54:01.535263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa836b07dfe6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('scope', sa.Integer(), nullable=False),
    sa.Column('category_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('activity_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('co2_factor', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('ch4_factor', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('n2o_factor', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('co2e_factor', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('activity_unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('factor_unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wtt_factor_id', sa.Uuid(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wtt_factor_id'], ['emission_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_factors_activity_key'), 'emission_factors', ['activity_key'], unique=False)
    op.create_index(op.f('ix_emission_factors_category_code'), 'emission_factors', ['category_code'], unique=False)
    op.create_index(op.f('ix_emission_factors_region'), 'emission_factors', ['region'], unique=False)
    op.create_index(op.f('ix_emission_factors_scope'), 'emission_factors', ['scope'], unique=False)
    op.create_index(op.f('ix_emission_factors_year'), 'emission_factors', ['year'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('industry_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('base_year', sa.Integer(), nullable=True),
    sa.Column('default_region', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('unit_conversions',
    sa.Column('from_unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('to_unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reporting_periods',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporting_periods_organization_id'), 'reporting_periods', ['organization_id'], unique=False)
    op.create_table('sites',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('grid_region', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('role', sa.Enum('VIEWER', 'EDITOR', 'ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('activities',
    sa.Column('scope', sa.Integer(), nullable=False),
    sa.Column('category_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('activity_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('calculation_method', sa.Enum('ACTIVITY', 'SPEND', 'DISTANCE', 'SUPPLIER', name='calculationmethod'), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('reporting_period_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('data_source', sa.Enum('MANUAL', 'IMPORT', 'API', name='datasource'), nullable=False),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_key'), 'activities', ['activity_key'], unique=False)
    op.create_index(op.f('ix_activities_organization_id'), 'activities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_activities_reporting_period_id'), 'activities', ['reporting_period_id'], unique=False)
    op.create_table('emissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('emission_factor_id', sa.Uuid(), nullable=False),
    sa.Column('co2_kg', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('ch4_kg', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('n2o_kg', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('co2e_kg', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('wtt_co2e_kg', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('converted_quantity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('converted_unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('formula', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel'), nullable=False),
    sa.Column('resolution_strategy', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('recalculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emissions_activity_id'), 'emissions', ['activity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emissions_activity_id'), table_name='emissions')
    op.drop_table('emissions')
    op.drop_index(op.f('ix_activities_reporting_period_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_organization_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_key'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_reporting_periods_organization_id'), table_name='reporting_periods')
    op.drop_table('reporting_periods')
    op.drop_table('unit_conversions')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_emission_factors_year'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_scope'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_region'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_category_code'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_activity_key'), table_name='emission_factors')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
