"""add org setup_complete and module_waitlist

Revision ID: bd6bedf13533
Revises: h7i8j9k0l1m2
Create Date: 2026-07-05 12:14:47.216326

Scoped to only the intended changes:
  - organizations.setup_complete (bool, default false)
  - organizations.setup_completed_at (nullable datetime)
  - module_waitlist table (+ indexes)
Autogenerated drift on other tables was intentionally removed.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "bd6bedf13533"
down_revision: Union[str, None] = "h7i8j9k0l1m2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "module_waitlist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column(
            "module_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_module_waitlist_created_at"),
        "module_waitlist",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_module_waitlist_email"), "module_waitlist", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_module_waitlist_module_id"),
        "module_waitlist",
        ["module_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_module_waitlist_organization_id"),
        "module_waitlist",
        ["organization_id"],
        unique=False,
    )
    op.add_column(
        "organizations",
        sa.Column(
            "setup_complete", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "organizations",
        sa.Column("setup_completed_at", sa.DateTime(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("organizations", "setup_completed_at")
    op.drop_column("organizations", "setup_complete")
    op.drop_index(
        op.f("ix_module_waitlist_organization_id"), table_name="module_waitlist"
    )
    op.drop_index(op.f("ix_module_waitlist_module_id"), table_name="module_waitlist")
    op.drop_index(op.f("ix_module_waitlist_email"), table_name="module_waitlist")
    op.drop_index(op.f("ix_module_waitlist_created_at"), table_name="module_waitlist")
    op.drop_table("module_waitlist")
