"""
Seed data for the Initiative Library.
These pre-built initiatives are matched to client's emission data via applicable_activity_keys.
"""
from decimal import Decimal
from uuid import uuid4

from app.models.decarbonization import Initiative, InitiativeCategory, ComplexityLevel


def get_initiative_seeds() -> list[dict]:
    """
    Returns seed data for initiatives.
    Each initiative specifies which activity_keys it applies to.
    """
    return [
        # =====================================================================
        # ENERGY EFFICIENCY
        # =====================================================================
        {
            "category": InitiativeCategory.ENERGY_EFFICIENCY,
            "subcategory": "Lighting",
            "name": "LED Lighting Retrofit",
            "short_description": "Replace conventional lighting with LED technology across facilities.",
            "detailed_description": "LED lighting uses 75% less energy than incandescent and lasts 25 times longer. This initiative involves auditing current lighting, replacing fixtures with LEDs, and implementing smart controls for occupancy-based lighting.",
            "applicable_scopes": [2],
            "applicable_category_codes": ["2"],
            "applicable_activity_keys": ["electricity_kwh"],
            "typical_reduction_percent_min": Decimal("8"),
            "typical_reduction_percent_max": Decimal("15"),
            "typical_reduction_percent_median": Decimal("12"),
            "typical_capex_per_tco2e_reduced": Decimal("150"),
            "typical_opex_change_percent": Decimal("-20"),
            "typical_payback_years_min": Decimal("1.5"),
            "typical_payback_years_max": Decimal("3"),
            "complexity": ComplexityLevel.LOW,
            "implementation_time_months_min": 1,
            "implementation_time_months_max": 6,
            "co_benefits": ["Reduced maintenance costs", "Improved lighting quality", "Longer bulb lifespan"],
            "common_barriers": ["Upfront cost", "Disruption during installation"],
            "min_emissions_for_relevance_tco2e": Decimal("50"),
        },
        {
            "category": InitiativeCategory.ENERGY_EFFICIENCY,
            "subcategory": "HVAC",
            "name": "HVAC System Optimization",
            "short_description": "Optimize heating, ventilation, and air conditioning systems for efficiency.",
            "detailed_description": "Includes installing programmable thermostats, regular maintenance schedules, upgrading to high-efficiency units, and implementing building management systems (BMS) for intelligent climate control.",
            "applicable_scopes": [1, 2],
            "applicable_category_codes": ["1.1", "2"],
            "applicable_activity_keys": ["electricity_kwh", "natural_gas_volume", "natural_gas_kwh", "heating_kwh", "cooling_kwh"],
            "typical_reduction_percent_min": Decimal("15"),
            "typical_reduction_percent_max": Decimal("30"),
            "typical_reduction_percent_median": Decimal("22"),
            "typical_capex_per_tco2e_reduced": Decimal("250"),
            "typical_opex_change_percent": Decimal("-25"),
            "typical_payback_years_min": Decimal("2"),
            "typical_payback_years_max": Decimal("5"),
            "complexity": ComplexityLevel.MEDIUM,
            "implementation_time_months_min": 3,
            "implementation_time_months_max": 12,
            "co_benefits": ["Improved comfort", "Reduced maintenance", "Extended equipment life"],
            "common_barriers": ["Capital investment", "Technical complexity", "Business disruption"],
            "min_emissions_for_relevance_tco2e": Decimal("100"),
        },
        {
            "category": InitiativeCategory.ENERGY_EFFICIENCY,
            "subcategory": "Building Envelope",
            "name": "Building Envelope Improvements",
            "short_description": "Improve insulation, windows, and air sealing to reduce energy loss.",
            "detailed_description": "Comprehensive upgrade including wall/roof insulation, double/triple glazed windows, air sealing, and thermal bridging reduction. Reduces heating and cooling demand significantly.",
            "applicable_scopes": [1, 2],
            "applicable_category_codes": ["1.1", "2"],
            "applicable_activity_keys": ["electricity_kwh", "natural_gas_volume", "natural_gas_kwh", "heating_kwh", "cooling_kwh"],
            "typical_reduction_percent_min": Decimal("20"),
            "typical_reduction_percent_max": Decimal("40"),
            "typical_reduction_percent_median": Decimal("30"),
            "typical_capex_per_tco2e_reduced": Decimal("500"),
            "typical_opex_change_percent": Decimal("-30"),
            "typical_payback_years_min": Decimal("5"),
            "typical_payback_years_max": Decimal("12"),
            "complexity": ComplexityLevel.HIGH,
            "implementation_time_months_min": 6,
            "implementation_time_months_max": 24,
            "co_benefits": ["Improved comfort", "Noise reduction", "Increased property value"],
            "common_barriers": ["High upfront cost", "Building disruption", "Heritage/aesthetic constraints"],
            "min_emissions_for_relevance_tco2e": Decimal("200"),
        },
        {
            "category": InitiativeCategory.ENERGY_EFFICIENCY,
            "subcategory": "Equipment",
            "name": "Energy-Efficient Equipment Upgrade",
            "short_description": "Replace old equipment with high-efficiency models (motors, compressors, etc.).",
            "detailed_description": "Systematic replacement of energy-intensive equipment with best-in-class efficient alternatives. Focus on motors, compressors, pumps, and process equipment.",
            "applicable_scopes": [1, 2],
            "applicable_category_codes": ["1.1", "2"],
            "applicable_activity_keys": ["electricity_kwh", "natural_gas_volume"],
            "typical_reduction_percent_min": Decimal("10"),
            "typical_reduction_percent_max": Decimal("25"),
            "typical_reduction_percent_median": Decimal("18"),
            "typical_capex_per_tco2e_reduced": Decimal("300"),
            "typical_opex_change_percent": Decimal("-20"),
            "typical_payback_years_min": Decimal("3"),
            "typical_payback_years_max": Decimal("7"),
            "complexity": ComplexityLevel.MEDIUM,
            "implementation_time_months_min": 3,
            "implementation_time_months_max": 18,
            "co_benefits": ["Reduced maintenance", "Improved reliability", "Lower operating costs"],
            "common_barriers": ["Capital requirements", "Equipment lead times", "Production disruption"],
            "min_emissions_for_relevance_tco2e": Decimal("100"),
        },

        # =====================================================================
        # RENEWABLE ENERGY
        # =====================================================================
        {
            "category": InitiativeCategory.RENEWABLE_ENERGY,
            "subcategory": "Solar",
            "name": "On-site Solar PV Installation",
            "short_description": "Install rooftop or ground-mounted solar panels for on-site renewable electricity.",
            "detailed_description": "Photovoltaic solar installation sized for facility consumption. Includes roof structural assessment, system design, installation, grid connection, and monitoring systems.",
            "applicable_scopes": [2],
            "applicable_category_codes": ["2"],
            "applicable_activity_keys": ["electricity_kwh"],
            "typical_reduction_percent_min": Decimal("30"),
            "typical_reduction_percent_max": Decimal("80"),
            "typical_reduction_percent_median": Decimal("50"),
            "typical_capex_per_tco2e_reduced": Decimal("800"),
            "typical_opex_change_percent": Decimal("-40"),
            "typical_payback_years_min": Decimal("4"),
            "typical_payback_years_max": Decimal("10"),
            "complexity": ComplexityLevel.MEDIUM,
            "implementation_time_months_min": 6,
            "implementation_time_months_max": 18,
            "co_benefits": ["Energy cost savings", "Energy independence", "Brand value", "LEED/BREEAM credits"],
            "common_barriers": ["Roof space limitations", "Upfront capital", "Grid connection delays", "Shading issues"],
            "min_emissions_for_relevance_tco2e": Decimal("100"),
        },
        {
            "category": InitiativeCategory.RENEWABLE_ENERGY,
            "subcategory": "PPA",
            "name": "Renewable Energy Power Purchase Agreement (PPA)",
            "short_description": "Contract to purchase renewable electricity from off-site solar or wind farms.",
            "detailed_description": "Long-term agreement (10-20 years) to purchase renewable electricity at fixed or indexed prices. Can be physical (delivery) or virtual (financial settlement). Provides additionality for new renewable capacity.",
            "applicable_scopes": [2],
            "applicable_category_codes": ["2"],
            "applicable_activity_keys": ["electricity_kwh"],
            "typical_reduction_percent_min": Decimal("80"),
            "typical_reduction_percent_max": Decimal("100"),
            "typical_reduction_percent_median": Decimal("95"),
            "typical_capex_per_tco2e_reduced": Decimal("50"),
            "typical_opex_change_percent": Decimal("-10"),
            "typical_payback_years_min": Decimal("0"),
            "typical_payback_years_max": Decimal("2"),
            "complexity": ComplexityLevel.MEDIUM,
            "implementation_time_months_min": 6,
            "implementation_time_months_max": 18,
            "co_benefits": ["Price stability", "RE100 eligibility", "Brand value", "No capital outlay"],
            "common_barriers": ["Long-term commitment", "Credit requirements", "Complexity of contracts"],
            "min_emissions_for_relevance_tco2e": Decimal("200"),
        },
        {
            "category": InitiativeCategory.RENEWABLE_ENERGY,
            "subcategory": "Green Tariff",
            "name": "Green Electricity Tariff",
            "short_description": "Switch to a certified green electricity tariff from your utility provider.",
            "detailed_description": "Purchase electricity backed by Guarantees of Origin (GOs) or Renewable Energy Certificates (RECs). Quick to implement but lower additionality than PPAs.",
            "applicable_scopes": [2],
            "applicable_category_codes": ["2"],
            "applicable_activity_keys": ["electricity_kwh"],
            "typical_reduction_percent_min": Decimal("80"),
            "typical_reduction_percent_max": Decimal("100"),
            "typical_reduction_percent_median": Decimal("90"),
            "typical_capex_per_tco2e_reduced": Decimal("20"),
            "typical_opex_change_percent": Decimal("5"),
            "typical_payback_years_min": Decimal("0"),
            "typical_payback_years_max": Decimal("1"),
            "complexity": ComplexityLevel.LOW,
            "implementation_time_months_min": 1,
            "implementation_time_months_max": 3,
            "co_benefits": ["Quick implementation", "No capital required", "Flexibility"],
            "common_barriers": ["Premium costs", "Lower additionality", "Greenwashing concerns"],
            "min_emissions_for_relevance_tco2e": Decimal("50"),
        },

        # =====================================================================
        # FLEET & TRANSPORT
        # =====================================================================
        {
            "category": InitiativeCategory.FLEET_TRANSPORT,
            "subcategory": "Electrification",
            "name": "Electric Vehicle Fleet Transition",
            "short_description": "Replace internal combustion engine vehicles with electric vehicles.",
            "detailed_description": "Phased replacement of fleet vehicles with EVs, including charging infrastructure installation, driver training, and route optimization for range requirements.",
            "applicable_scopes": [1],
            "applicable_category_codes": ["1.1"],
            "applicable_activity_keys": ["diesel_volume", "petrol_volume", "company_car_km"],
            "typical_reduction_percent_min": Decimal("60"),
            "typical_reduction_percent_max": Decimal("100"),
            "typical_reduction_percent_median": Decimal("80"),
            "typical_capex_per_tco2e_reduced": Decimal("1200"),
            "typical_opex_change_percent": Decimal("-30"),
            "typical_payback_years_min": Decimal("5"),
            "typical_payback_years_max": Decimal("10"),
            "complexity": ComplexityLevel.HIGH,
            "implementation_time_months_min": 12,
            "implementation_time_months_max": 48,
            "co_benefits": ["Lower fuel costs", "Reduced maintenance", "Brand image", "Employee attraction"],
            "common_barriers": ["High vehicle cost", "Charging infrastructure", "Range anxiety", "Vehicle availability"],
            "min_emissions_for_relevance_tco2e": Decimal("100"),
        },
        {
            "category": InitiativeCategory.FLEET_TRANSPORT,
            "subcategory": "Optimization",
            "name": "Fleet Route Optimization",
            "short_description": "Implement route optimization software to reduce fuel consumption and mileage.",
            "detailed_description": "Deploy telematics and route optimization systems to minimize distance traveled, reduce idle time, and improve delivery efficiency.",
            "applicable_scopes": [1],
            "applicable_category_codes": ["1.1"],
            "applicable_activity_keys": ["diesel_volume", "petrol_volume", "company_car_km"],
            "typical_reduction_percent_min": Decimal("10"),
            "typical_reduction_percent_max": Decimal("20"),
            "typical_reduction_percent_median": Decimal("15"),
            "typical_capex_per_tco2e_reduced": Decimal("100"),
            "typical_opex_change_percent": Decimal("-15"),
            "typical_payback_years_min": Decimal("0.5"),
            "typical_payback_years_max": Decimal("2"),
            "complexity": ComplexityLevel.LOW,
            "implementation_time_months_min": 1,
            "implementation_time_months_max": 6,
            "co_benefits": ["Fuel savings", "Reduced vehicle wear", "Improved service levels"],
            "common_barriers": ["Driver resistance", "System integration", "Training needs"],
            "min_emissions_for_relevance_tco2e": Decimal("50"),
        },
        {
            "category": InitiativeCategory.FLEET_TRANSPORT,
            "subcategory": "Driver Training",
            "name": "Eco-Driving Training Program",
            "short_description": "Train drivers in fuel-efficient driving techniques.",
            "detailed_description": "Comprehensive driver training program covering smooth acceleration, optimal gear shifting, speed management, and vehicle maintenance awareness.",
            "applicable_scopes": [1],
            "applicable_category_codes": ["1.1"],
            "applicable_activity_keys": ["diesel_volume", "petrol_volume", "company_car_km"],
            "typical_reduction_percent_min": Decimal("5"),
            "typical_reduction_percent_max": Decimal("15"),
            "typical_reduction_percent_median": Decimal("10"),
            "typical_capex_per_tco2e_reduced": Decimal("30"),
            "typical_opex_change_percent": Decimal("-10"),
            "typical_payback_years_min": Decimal("0.5"),
            "typical_payback_years_max": Decimal("1.5"),
            "complexity": ComplexityLevel.LOW,
            "implementation_time_months_min": 1,
            "implementation_time_months_max": 3,
            "co_benefits": ["Fuel savings", "Reduced accidents", "Vehicle longevity"],
            "common_barriers": ["Behavior change", "Ongoing reinforcement needed"],
            "min_emissions_for_relevance_tco2e": Decimal("30"),
        },

        # =====================================================================
        # BUSINESS TRAVEL
        # =====================================================================
        {
            "category": InitiativeCategory.BEHAVIOR_CHANGE,
            "subcategory": "Travel Policy",
            "name": "Video Conferencing First Policy",
            "short_description": "Implement policy requiring video conferencing as default before business travel.",
            "detailed_description": "Establish mandatory consideration of video conferencing alternatives before approving business travel. Invest in high-quality VC equipment and training.",
            "applicable_scopes": [3],
            "applicable_category_codes": ["3.6"],
            "applicable_activity_keys": ["flight_economy_km", "flight_business_km", "flight_first_km", "hotel_nights"],
            "typical_reduction_percent_min": Decimal("30"),
            "typical_reduction_percent_max": Decimal("50"),
            "typical_reduction_percent_median": Decimal("40"),
            "typical_capex_per_tco2e_reduced": Decimal("50"),
            "typical_opex_change_percent": Decimal("-60"),
            "typical_payback_years_min": Decimal("0.5"),
            "typical_payback_years_max": Decimal("1"),
            "complexity": ComplexityLevel.LOW,
            "implementation_time_months_min": 1,
            "implementation_time_months_max": 3,
            "co_benefits": ["Travel cost savings", "Work-life balance", "Productivity gains"],
            "common_barriers": ["Culture change", "Client expectations", "Relationship building needs"],
            "min_emissions_for_relevance_tco2e": Decimal("50"),
        },
        {
            "category": InitiativeCategory.BEHAVIOR_CHANGE,
            "subcategory": "Travel Policy",
            "name": "Rail for Short-Haul Travel Policy",
            "short_description": "Mandate rail travel instead of flying for journeys under 4 hours.",
            "detailed_description": "Policy requiring train travel for routes where rail journey time is under 4 hours. Applicable where good rail connections exist.",
            "applicable_scopes": [3],
            "applicable_category_codes": ["3.6"],
            "applicable_activity_keys": ["flight_economy_km", "flight_business_km"],
            "typical_reduction_percent_min": Decimal("15"),
            "typical_reduction_percent_max": Decimal("30"),
            "typical_reduction_percent_median": Decimal("22"),
            "typical_capex_per_tco2e_reduced": Decimal("10"),
            "typical_opex_change_percent": Decimal("-20"),
            "typical_payback_years_min": Decimal("0"),
            "typical_payback_years_max": Decimal("0.5"),
            "complexity": ComplexityLevel.LOW,
            "implementation_time_months_min": 1,
            "implementation_time_months_max": 2,
            "co_benefits": ["Cost savings on short routes", "Productive travel time", "Reliability"],
            "common_barriers": ["Rail connectivity", "Journey time", "Booking complexity"],
            "min_emissions_for_relevance_tco2e": Decimal("30"),
            "applicable_regions": ["Europe", "Japan", "UK"],
        },
        {
            "category": InitiativeCategory.CARBON_REMOVAL,
            "subcategory": "SAF",
            "name": "Sustainable Aviation Fuel (SAF) Purchasing",
            "short_description": "Purchase sustainable aviation fuel certificates to reduce flight emissions.",
            "detailed_description": "Invest in SAF through airline programs or certificate schemes. SAF is made from sustainable feedstocks and can reduce lifecycle emissions by up to 80%.",
            "applicable_scopes": [3],
            "applicable_category_codes": ["3.6"],
            "applicable_activity_keys": ["flight_economy_km", "flight_business_km", "flight_first_km"],
            "typical_reduction_percent_min": Decimal("50"),
            "typical_reduction_percent_max": Decimal("80"),
            "typical_reduction_percent_median": Decimal("65"),
            "typical_capex_per_tco2e_reduced": Decimal("200"),
            "typical_opex_change_percent": Decimal("0"),
            "typical_payback_years_min": None,
            "typical_payback_years_max": None,
            "complexity": ComplexityLevel.MEDIUM,
            "implementation_time_months_min": 1,
            "implementation_time_months_max": 6,
            "co_benefits": ["Industry transition support", "Clear insetting mechanism"],
            "common_barriers": ["Cost premium", "Limited availability", "Additionality questions"],
            "min_emissions_for_relevance_tco2e": Decimal("100"),
        },

        # =====================================================================
        # SUPPLY CHAIN
        # =====================================================================
        {
            "category": InitiativeCategory.SUPPLY_CHAIN,
            "subcategory": "Engagement",
            "name": "Supplier Engagement Program",
            "short_description": "Work with key suppliers to reduce emissions in your supply chain.",
            "detailed_description": "Structured program to engage top suppliers on emissions measurement, target-setting, and reduction initiatives. Includes supplier scoring, capacity building, and collaborative reduction projects.",
            "applicable_scopes": [3],
            "applicable_category_codes": ["3.1", "3.2"],
            "applicable_activity_keys": [
                "purchased_goods_plastic", "purchased_goods_steel", "purchased_goods_aluminum",
                "purchased_goods_paper", "purchased_goods_chemicals", "purchased_goods_electronics",
                "purchased_goods_textiles", "purchased_services_spend"
            ],
            "typical_reduction_percent_min": Decimal("10"),
            "typical_reduction_percent_max": Decimal("30"),
            "typical_reduction_percent_median": Decimal("18"),
            "typical_capex_per_tco2e_reduced": Decimal("80"),
            "typical_opex_change_percent": Decimal("-5"),
            "typical_payback_years_min": Decimal("2"),
            "typical_payback_years_max": Decimal("5"),
            "complexity": ComplexityLevel.HIGH,
            "implementation_time_months_min": 12,
            "implementation_time_months_max": 36,
            "co_benefits": ["Supply chain resilience", "Supplier relationships", "Risk reduction"],
            "common_barriers": ["Supplier capacity", "Data availability", "Limited leverage with suppliers"],
            "min_emissions_for_relevance_tco2e": Decimal("500"),
        },
        {
            "category": InitiativeCategory.SUPPLY_CHAIN,
            "subcategory": "Materials",
            "name": "Recycled Content Procurement",
            "short_description": "Increase procurement of materials with recycled content.",
            "detailed_description": "Shift procurement to materials with higher recycled content (recycled plastics, secondary steel/aluminum, recycled paper). Set minimum recycled content requirements.",
            "applicable_scopes": [3],
            "applicable_category_codes": ["3.1"],
            "applicable_activity_keys": [
                "purchased_goods_plastic", "purchased_goods_steel", "purchased_goods_aluminum",
                "purchased_goods_paper"
            ],
            "typical_reduction_percent_min": Decimal("20"),
            "typical_reduction_percent_max": Decimal("60"),
            "typical_reduction_percent_median": Decimal("35"),
            "typical_capex_per_tco2e_reduced": Decimal("100"),
            "typical_opex_change_percent": Decimal("10"),
            "typical_payback_years_min": Decimal("3"),
            "typical_payback_years_max": Decimal("8"),
            "complexity": ComplexityLevel.MEDIUM,
            "implementation_time_months_min": 6,
            "implementation_time_months_max": 24,
            "co_benefits": ["Circular economy alignment", "Resource security", "Brand value"],
            "common_barriers": ["Availability", "Quality concerns", "Price premium"],
            "min_emissions_for_relevance_tco2e": Decimal("200"),
        },
        {
            "category": InitiativeCategory.SUPPLY_CHAIN,
            "subcategory": "Logistics",
            "name": "Local Sourcing Initiative",
            "short_description": "Shift to local suppliers to reduce transportation emissions.",
            "detailed_description": "Identify opportunities to source materials and components from local suppliers, reducing freight transport distances and associated emissions.",
            "applicable_scopes": [3],
            "applicable_category_codes": ["3.4"],
            "applicable_activity_keys": [
                "upstream_transport_road", "upstream_transport_sea", "upstream_transport_air",
                "truck_freight_tkm", "sea_freight_tkm", "air_freight_tkm"
            ],
            "typical_reduction_percent_min": Decimal("15"),
            "typical_reduction_percent_max": Decimal("40"),
            "typical_reduction_percent_median": Decimal("25"),
            "typical_capex_per_tco2e_reduced": Decimal("50"),
            "typical_opex_change_percent": Decimal("-5"),
            "typical_payback_years_min": Decimal("1"),
            "typical_payback_years_max": Decimal("3"),
            "complexity": ComplexityLevel.MEDIUM,
            "implementation_time_months_min": 6,
            "implementation_time_months_max": 24,
            "co_benefits": ["Supply chain resilience", "Shorter lead times", "Local economic support"],
            "common_barriers": ["Supplier availability", "Cost differences", "Quality assurance"],
            "min_emissions_for_relevance_tco2e": Decimal("100"),
        },

        # =====================================================================
        # WASTE REDUCTION
        # =====================================================================
        {
            "category": InitiativeCategory.WASTE_REDUCTION,
            "subcategory": "Diversion",
            "name": "Zero Waste to Landfill Program",
            "short_description": "Implement comprehensive waste diversion to eliminate landfill waste.",
            "detailed_description": "Establish sorting, recycling, composting, and waste-to-energy programs to divert waste from landfill. Target 90%+ diversion rate.",
            "applicable_scopes": [3],
            "applicable_category_codes": ["3.5"],
            "applicable_activity_keys": [
                "waste_landfill_mixed", "waste_landfill_organic", "waste_recycling",
                "waste_incineration", "waste_composting"
            ],
            "typical_reduction_percent_min": Decimal("40"),
            "typical_reduction_percent_max": Decimal("80"),
            "typical_reduction_percent_median": Decimal("60"),
            "typical_capex_per_tco2e_reduced": Decimal("200"),
            "typical_opex_change_percent": Decimal("-10"),
            "typical_payback_years_min": Decimal("2"),
            "typical_payback_years_max": Decimal("5"),
            "complexity": ComplexityLevel.MEDIUM,
            "implementation_time_months_min": 6,
            "implementation_time_months_max": 18,
            "co_benefits": ["Waste cost reduction", "Resource recovery revenue", "Brand value"],
            "common_barriers": ["Infrastructure needs", "Employee behavior change", "Contamination"],
            "min_emissions_for_relevance_tco2e": Decimal("30"),
        },
        {
            "category": InitiativeCategory.WASTE_REDUCTION,
            "subcategory": "Prevention",
            "name": "Waste Prevention Program",
            "short_description": "Reduce waste generation at source through design and process changes.",
            "detailed_description": "Focus on waste prevention through packaging optimization, material efficiency, reusable containers, and process improvements that generate less waste.",
            "applicable_scopes": [3],
            "applicable_category_codes": ["3.5"],
            "applicable_activity_keys": [
                "waste_landfill_mixed", "waste_landfill_organic", "waste_recycling"
            ],
            "typical_reduction_percent_min": Decimal("20"),
            "typical_reduction_percent_max": Decimal("50"),
            "typical_reduction_percent_median": Decimal("30"),
            "typical_capex_per_tco2e_reduced": Decimal("100"),
            "typical_opex_change_percent": Decimal("-20"),
            "typical_payback_years_min": Decimal("1"),
            "typical_payback_years_max": Decimal("3"),
            "complexity": ComplexityLevel.MEDIUM,
            "implementation_time_months_min": 3,
            "implementation_time_months_max": 12,
            "co_benefits": ["Material cost savings", "Reduced handling", "Circular economy"],
            "common_barriers": ["Process changes required", "Supplier coordination"],
            "min_emissions_for_relevance_tco2e": Decimal("20"),
        },

        # =====================================================================
        # PROCESS CHANGES
        # =====================================================================
        {
            "category": InitiativeCategory.PROCESS_CHANGE,
            "subcategory": "Fugitive",
            "name": "Refrigerant Leak Detection and Repair (LDAR)",
            "short_description": "Implement systematic leak detection to reduce refrigerant fugitive emissions.",
            "detailed_description": "Regular inspection program using infrared cameras or other detection methods, combined with rapid repair protocols and low-GWP refrigerant transitions.",
            "applicable_scopes": [1],
            "applicable_category_codes": ["1.3"],
            "applicable_activity_keys": [
                "refrigerant_r134a", "refrigerant_r410a", "refrigerant_r32"
            ],
            "typical_reduction_percent_min": Decimal("50"),
            "typical_reduction_percent_max": Decimal("90"),
            "typical_reduction_percent_median": Decimal("70"),
            "typical_capex_per_tco2e_reduced": Decimal("50"),
            "typical_opex_change_percent": Decimal("-30"),
            "typical_payback_years_min": Decimal("0.5"),
            "typical_payback_years_max": Decimal("2"),
            "complexity": ComplexityLevel.MEDIUM,
            "implementation_time_months_min": 3,
            "implementation_time_months_max": 12,
            "co_benefits": ["Refrigerant cost savings", "Equipment efficiency", "Regulatory compliance"],
            "common_barriers": ["Technical expertise", "Access to equipment", "Ongoing monitoring needs"],
            "min_emissions_for_relevance_tco2e": Decimal("20"),
        },
        {
            "category": InitiativeCategory.PROCESS_CHANGE,
            "subcategory": "Fuel Switch",
            "name": "Natural Gas to Electrification",
            "short_description": "Replace natural gas heating/processes with electric alternatives.",
            "detailed_description": "Convert gas-fired heating, boilers, and process equipment to electric alternatives (heat pumps, electric boilers). Most effective in regions with clean electricity grids.",
            "applicable_scopes": [1],
            "applicable_category_codes": ["1.1"],
            "applicable_activity_keys": ["natural_gas_volume", "natural_gas_kwh"],
            "typical_reduction_percent_min": Decimal("50"),
            "typical_reduction_percent_max": Decimal("100"),
            "typical_reduction_percent_median": Decimal("75"),
            "typical_capex_per_tco2e_reduced": Decimal("600"),
            "typical_opex_change_percent": Decimal("-20"),
            "typical_payback_years_min": Decimal("5"),
            "typical_payback_years_max": Decimal("12"),
            "complexity": ComplexityLevel.HIGH,
            "implementation_time_months_min": 12,
            "implementation_time_months_max": 36,
            "co_benefits": ["Operational simplicity", "No on-site combustion", "Grid flexibility"],
            "common_barriers": ["High capital cost", "Electrical infrastructure upgrades", "Process compatibility"],
            "min_emissions_for_relevance_tco2e": Decimal("200"),
            "applicable_regions": ["Europe", "US", "UK"],
        },

        # =====================================================================
        # EMPLOYEE COMMUTING
        # =====================================================================
        {
            "category": InitiativeCategory.BEHAVIOR_CHANGE,
            "subcategory": "Commuting",
            "name": "Remote Work Policy",
            "short_description": "Implement flexible remote work policy to reduce commuting emissions.",
            "detailed_description": "Formal policy allowing employees to work from home 2-3 days per week, reducing commuting-related emissions. Includes home office support and digital collaboration tools.",
            "applicable_scopes": [3],
            "applicable_category_codes": ["3.7"],
            "applicable_activity_keys": ["commute_car_km", "commute_public_transit", "remote_work_days"],
            "typical_reduction_percent_min": Decimal("30"),
            "typical_reduction_percent_max": Decimal("50"),
            "typical_reduction_percent_median": Decimal("40"),
            "typical_capex_per_tco2e_reduced": Decimal("30"),
            "typical_opex_change_percent": Decimal("-20"),
            "typical_payback_years_min": Decimal("0"),
            "typical_payback_years_max": Decimal("1"),
            "complexity": ComplexityLevel.LOW,
            "implementation_time_months_min": 1,
            "implementation_time_months_max": 3,
            "co_benefits": ["Office space savings", "Employee satisfaction", "Talent attraction"],
            "common_barriers": ["Culture change", "Management trust", "Collaboration concerns"],
            "min_emissions_for_relevance_tco2e": Decimal("50"),
        },
        {
            "category": InitiativeCategory.BEHAVIOR_CHANGE,
            "subcategory": "Commuting",
            "name": "EV Charging for Employees",
            "short_description": "Install EV charging stations at workplace for employee commuting.",
            "detailed_description": "Install Level 2 EV charging infrastructure at office locations to support employee EV adoption and reduce commuting emissions.",
            "applicable_scopes": [3],
            "applicable_category_codes": ["3.7"],
            "applicable_activity_keys": ["commute_car_km"],
            "typical_reduction_percent_min": Decimal("20"),
            "typical_reduction_percent_max": Decimal("40"),
            "typical_reduction_percent_median": Decimal("30"),
            "typical_capex_per_tco2e_reduced": Decimal("150"),
            "typical_opex_change_percent": Decimal("5"),
            "typical_payback_years_min": Decimal("3"),
            "typical_payback_years_max": Decimal("7"),
            "complexity": ComplexityLevel.MEDIUM,
            "implementation_time_months_min": 3,
            "implementation_time_months_max": 9,
            "co_benefits": ["Employee benefit", "EV adoption support", "Brand value"],
            "common_barriers": ["Parking space limitations", "Electrical capacity", "Usage management"],
            "min_emissions_for_relevance_tco2e": Decimal("30"),
        },
    ]


async def seed_initiatives(session) -> int:
    """
    Seed the initiatives table with pre-defined initiatives.
    Returns the number of initiatives created.
    """
    from sqlmodel import select

    # Check if initiatives already exist
    result = await session.execute(select(Initiative).limit(1))
    if result.scalar_one_or_none():
        return 0  # Already seeded

    initiatives_data = get_initiative_seeds()
    count = 0

    for data in initiatives_data:
        initiative = Initiative(**data)
        session.add(initiative)
        count += 1

    await session.commit()
    return count
